//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.Composition;
using System.Windows.Media;
using GammaJul.ForTea.Core.Daemon.Attributes;
using JetBrains.Platform.VisualStudio.SinceVs10.TextControl.Markup.FormatDefinitions;
using Microsoft.VisualStudio.Text.Classification;
using Microsoft.VisualStudio.Utilities;
using JetBrains.TextControl.DocumentMarkup;

namespace JetBrains.ForTea.ReSharperPlugin.Daemon.Attributes
{
    #region registration
    [RegisterHighlighter(
	    T4HighlightingAttributeIds.T4_SPECIFIC_STRING,
	    GroupId = T4HighlightingAttributeGroup.ID,
	    EffectType = EffectType.TEXT,
	    ForegroundColor = "#A31515",
        DarkForegroundColor = "#D69D85"

    )]
    [RegisterHighlighter(
	    T4HighlightingAttributeIds.T4_SPECIFIC_NUMBER,
	    GroupId = T4HighlightingAttributeGroup.ID,
	    EffectType = EffectType.TEXT,
	    ForegroundColor = "#000000",
        DarkForegroundColor = "#B5CEA8"

    )]
    [RegisterHighlighter(
	    T4HighlightingAttributeIds.T4_SPECIFIC_COMMENT,
	    GroupId = T4HighlightingAttributeGroup.ID,
	    EffectType = EffectType.TEXT,
	    ForegroundColor = "#007F00",
        DarkForegroundColor = "#57A64A"

    )]
    public class T4ReSharperAttributes
    {
    }
    #endregion
	#region block tag
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class BlockTagClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.BLOCK_TAG;

		public BlockTagClassificationFormatDefinition()
		{
			DisplayName = Name;
			BackgroundColor = Color.FromRgb(0xFB, 0xFB, 0x64);
			ForegroundColor = Color.FromRgb(0x00, 0x00, 0x00);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region directive
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class DirectiveClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.DIRECTIVE;

		public DirectiveClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0xEE, 0x82, 0xEE);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region directive attribute
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class DirectiveAttributeClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.DIRECTIVE_ATTRIBUTE;

		public DirectiveAttributeClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0x56, 0x9C, 0xD6);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region attribute value
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class AttributeValueClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.ATTRIBUTE_VALUE;

		public AttributeValueClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0x9C, 0x58, 0x00);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region macro
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class MacroClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.MACRO;

		public MacroClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0x56, 0x9C, 0xD6);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region environment variable
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class EnvironmentVariableClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.ENVIRONMENT_VARIABLE;

		public EnvironmentVariableClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0xB5, 0xCE, 0xA8);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region t4 specific string
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class T4SpecificStringClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.T4_SPECIFIC_STRING;

		public T4SpecificStringClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0xA3, 0x15, 0x15);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region t4 specific number
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class T4SpecificNumberClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.T4_SPECIFIC_NUMBER;

		public T4SpecificNumberClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0x00, 0x00, 0x00);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

	#region t4 specific comment
	[ClassificationType(ClassificationTypeNames = Name)]
	[Order(
		After = VsSyntaxPriorityClassificationDefinition.Name,
		Before = VsAnalysisPriorityClassificationDefinition.Name
	)]
	[Export(typeof(EditorFormatDefinition))]
	[Name(Name)]
	[System.ComponentModel.DisplayName(Name)]
	[UserVisible(true)]
	internal sealed class T4SpecificCommentClassificationFormatDefinition : ClassificationFormatDefinition
	{
		private const string Name = T4HighlightingAttributeIds.T4_SPECIFIC_COMMENT;

		public T4SpecificCommentClassificationFormatDefinition()
		{
			DisplayName = Name;
			ForegroundColor = Color.FromRgb(0x00, 0x7F, 0x00);
		}

		[Export, Name(Name), BaseDefinition("formal language")]
		internal ClassificationTypeDefinition ClassificationTypeDefinition;
	}
	#endregion

}
