// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using JetBrains.ForTea.ReSharperPlugin.Daemon.Highlightings;
using JetBrains.ReSharper.Feature.Services.Daemon.IdeaAttributes;
using JetBrains.TextControl.DocumentMarkup;
using GammaJul.ForTea.Core.Daemon.Attributes;

[assembly: RegisterHighlighter(
	T4ReSharperHighlightingAttributeIds.BLOCK_MARKER,
	EffectType = EffectType.TEXT,
	GroupId = T4HighlightingAttributeIds.T4,
	FallbackAttributeId = IdeaXmlHighlighterColorsAttributeIds.XML_TAG
)]
[assembly: RegisterHighlighter(
	T4ReSharperHighlightingAttributeIds.OPERATOR,
	EffectType = EffectType.TEXT,
	GroupId = T4HighlightingAttributeIds.T4,
	FallbackAttributeId = IdeaXmlHighlighterColorsAttributeIds.XML_ATTRIBUTE_VALUE
)]

namespace JetBrains.ForTea.ReSharperPlugin.Daemon.Highlightings
{
	public static class T4ReSharperHighlightingAttributeIds
	{
		public const string BLOCK_MARKER = "T4 Block Marker";
		public const string OPERATOR = "T4 Operator";
	}
}
