// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using JetBrains.ForTea.RiderPlugin.Features.Folding;
using JetBrains.TextControl.DocumentMarkup;

#region Registering
[assembly: RegisterHighlighter(T4CodeFoldingAttributes.Directive, EffectType = EffectType.FOLDING)]
[assembly: RegisterHighlighter(T4CodeFoldingAttributes.ExpressionBlock, EffectType = EffectType.FOLDING)]
[assembly: RegisterHighlighter(T4CodeFoldingAttributes.FeatureBlock, EffectType = EffectType.FOLDING)]
[assembly: RegisterHighlighter(T4CodeFoldingAttributes.StatementBlock, EffectType = EffectType.FOLDING)]
#endregion

namespace JetBrains.ForTea.RiderPlugin.Features.Folding
{
	public static class T4CodeFoldingAttributes
	{
		public const string Directive = "T4 Directive Folding";
		public const string ExpressionBlock = "T4 Expression Block Folding";
		public const string FeatureBlock = "T4 Feature Block Folding";
		public const string StatementBlock = "T4 Statement Block Folding";
	}
}
