// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GammaJul.ForTea.Core.Daemon.Attributes;
using JetBrains.ReSharper.Feature.Services.Daemon;
using JetBrains.ReSharper.Feature.Services.Daemon.IdeaAttributes;
using JetBrains.TextControl.DocumentMarkup;

[assembly: RegisterHighlighterGroup(
	T4HighlightingAttributeIds.T4,
	T4HighlightingAttributeIds.T4,
	HighlighterGroupPriority.LANGUAGE_SETTINGS,
	DemoText = "<#@ <T4_DIRECTIVE>assembly</T4_DIRECTIVE> <T4_DIRECTIVE_ATTRIBUTE>name</T4_DIRECTIVE_ATTRIBUTE>=\"<T4_ATTRIBUTE_VALUE>$(</T4_ATTRIBUTE_VALUE><T4_MACRO_VALUE>SolutionDir</T4_MACRO_VALUE><T4_ATTRIBUTE_VALUE>)/%</T4_ATTRIBUTE_VALUE><T4_ENVIRONMENT_VARIABLE>USERNAME</T4_ENVIRONMENT_VARIABLE><T4_ATTRIBUTE_VALUE>%<T4_ATTRIBUTE_VALUE>/Foo.dll</T4_ATTRIBUTE_VALUE>\"#>"
)]
[assembly: RegisterHighlighter(
    T4HighlightingAttributeIds.MACRO,
    EffectType = EffectType.TEXT,
    GroupId = T4HighlightingAttributeIds.T4,
    FallbackAttributeId = HighlightingAttributeIds.KEYWORD
)]
[assembly: RegisterHighlighter(
    T4HighlightingAttributeIds.ENVIRONMENT_VARIABLE,
    EffectType = EffectType.TEXT,
    GroupId = T4HighlightingAttributeIds.T4,
    FallbackAttributeId = HighlightingAttributeIds.NUMBER
)]
[assembly: RegisterHighlighter(
    T4HighlightingAttributeIds.RAW_ATTRIBUTE_VALUE,
    EffectType = EffectType.TEXT,
    GroupId = T4HighlightingAttributeIds.T4,
    FallbackAttributeId = IdeaXmlHighlighterColorsAttributeIds.XML_ATTRIBUTE_VALUE
)]
[assembly: RegisterHighlighter(
    T4HighlightingAttributeIds.DIRECTIVE,
    EffectType = EffectType.TEXT,
    GroupId = T4HighlightingAttributeIds.T4,
    FallbackAttributeId = IdeaXmlHighlighterColorsAttributeIds.XML_TAG
)]
[assembly: RegisterHighlighter(
    T4HighlightingAttributeIds.DIRECTIVE_ATTRIBUTE,
    EffectType = EffectType.TEXT,
    GroupId = T4HighlightingAttributeIds.T4,
    FallbackAttributeId = IdeaXmlHighlighterColorsAttributeIds.XML_ATTRIBUTE_NAME
)]

namespace GammaJul.ForTea.Core.Daemon.Attributes
{
	public static class T4HighlightingAttributeIds
	{
		public const string T4 = "T4";
		public const string MACRO = "T4 Macro";
		public const string ENVIRONMENT_VARIABLE = "T4 Environment Variable";
		public const string RAW_ATTRIBUTE_VALUE = "T4 Raw Attribute Value";
		public const string DIRECTIVE = "T4 Directive";
		public const string DIRECTIVE_ATTRIBUTE = "T4 Directive Attribute";
	}
}
